names:
- Bus
- Bike
- Car
- Pedestrian
- Truck
nc: 5
train:
- /mnt/data/FishEye8K/train-D/images
- /mnt/data/FishEye8K/train-D_naive_v0-gen/images
- /mnt/data/FishEye8K/train-D_automatic_v1-gen/images
val: /mnt/data/FishEye8K/test/images
val_json: /mnt/data/FishEye8K/test/test.json
